(function(w){const N=w.ZadoniCesta;N.categorias=[{id:'chocolates',nome:'Chocolates'},{id:'bebidas',nome:'Bebidas'},{id:'flores-decoracao',nome:'Flores e decoração'},{id:'presentes',nome:'Presentes'},{id:'tabua-frios-frutas',nome:'Tábua de frios e frutas'},{id:'adicionais',nome:'Adicionais'}];
// ATENÇÃO: substituir pelos preços, produtos e disponibilidade reais da Zadoni.
N.produtos=[
{id:'ferrero-rocher-12',nome:'Ferrero Rocher caixa 12 unidades',descricao:'Caixa com 12 unidades de Ferrero Rocher.',categoria:'chocolates',preco:6900,espaco:4,quantidadeMaxima:2,imagem:'assets/produtos/ferrero-rocher-caixa-12.webp',disponivel:true,destaque:true},
{id:'ferrero-rocher-10',nome:'Ferrero Rocher caixa 10 unidades',descricao:'Caixa com 10 unidades de Ferrero Rocher.',categoria:'chocolates',preco:5300,espaco:4,quantidadeMaxima:2,imagem:'assets/produtos/ferrero-rocher-caixa-8.webp',disponivel:true,destaque:true},
{id:'ferrero-rocher-4',nome:'Ferrero Rocher caixa 4 unidades',descricao:'Caixa com 4 unidades de Ferrero Rocher.',categoria:'chocolates',preco:3600,espaco:2,quantidadeMaxima:3,imagem:'assets/produtos/ferrero-rocher-caixa-4.webp',disponivel:true,destaque:true},
{id:'barrinha-cacau-show',nome:'Barrinha Cacau Show',descricao:'Barrinha Cacau Show para compor a cesta.',categoria:'chocolates',preco:900,espaco:1,quantidadeMaxima:10,imagem:'assets/produtos/barrinha-cacau-show.webp',disponivel:true,destaque:true},
{id:'bebida-especial',nome:'Bebida especial',descricao:'Bebida escolhida no fechamento pelo WhatsApp conforme disponibilidade.',categoria:'bebidas',preco:6300,espaco:3,quantidadeMaxima:3,imagem:'../assets/optimized/products/mimo-coca-cola-criativo.jpg',disponivel:true,destaque:true},
{id:'vinho-pergola',nome:'Vinho Pérgola',descricao:'Vinho Pérgola para composição especial.',categoria:'bebidas',preco:8000,espaco:6,quantidadeMaxima:1,imagem:'../assets/optimized/products/cesta-romantica-vinho-san-martin.jpg',disponivel:true,destaque:true},
{id:'bebida-cafe',nome:'Bebida para café',descricao:'Item para cesta de café da manhã.',categoria:'bebidas',preco:1800,espaco:2,quantidadeMaxima:3,imagem:'../assets/optimized/products/cesta-cafe-da-manha-especial.webp',disponivel:true,destaque:false},
{id:'arranjo-rosas-naturais',nome:'Arranjo de rosas naturais',descricao:'Arranjo de rosas naturais para colocar na cesta.',categoria:'flores-decoracao',preco:10700,espaco:5,quantidadeMaxima:1,imagem:'../assets/optimized/products/jarro-flor-natural-laco-rosa.jpg',disponivel:true,destaque:true},
{id:'arranjo-rosas-artificiais',nome:'Arranjo de rosas artificiais',descricao:'Arranjo de rosas artificiais para compor a cesta.',categoria:'flores-decoracao',preco:5300,espaco:3,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:true},
{id:'arranjo-vermelho',nome:'Arranjo vermelho',descricao:'Arranjo com presença para ocasiões especiais.',categoria:'flores-decoracao',preco:8900,espaco:5,quantidadeMaxima:1,imagem:'../assets/optimized/products/jarro-flores-naturais-vermelho.jpg',disponivel:true,destaque:true},
{id:'detalhe-girassol',nome:'Detalhe girassol',descricao:'Elemento alegre para decoração da cesta.',categoria:'flores-decoracao',preco:4400,espaco:3,quantidadeMaxima:2,imagem:'assets/produtos/girassol-artificial.webp',disponivel:true,destaque:false},
{id:'caneca-presente',nome:'Caneca para presente',descricao:'Caneca para deixar a cesta mais útil e afetiva.',categoria:'presentes',preco:4400,espaco:4,quantidadeMaxima:2,imagem:'../assets/optimized/products/cesta-masculina-azul-classica.jpg',disponivel:true,destaque:true},
{id:'pelucia',nome:'Pelúcia',descricao:'Pelúcia decorativa para complementar o presente.',categoria:'presentes',preco:7100,espaco:8,quantidadeMaxima:1,imagem:'assets/produtos/pelucia-ursinho-love.webp',disponivel:true,destaque:true},
{id:'perfume-bolso',nome:'Perfume de bolso',descricao:'Fragrância 15 ml conforme disponibilidade.',categoria:'presentes',preco:4500,espaco:2,quantidadeMaxima:3,imagem:'../assets/optimized/products/perfume-521-vip-rose-amakha-15ml.jpg',disponivel:true,destaque:true},
{id:'tabua-frios-pequena',nome:'Tábua de frios pequena',descricao:'Opção menor com frios, queijo e azeitonas. Valor estimado conforme itens disponíveis.',categoria:'tabua-frios-frutas',preco:10700,espaco:6,quantidadeMaxima:1,imagem:'assets/produtos/tabua-frios-simples.webp',disponivel:true,destaque:true},
{id:'tabua-frios-frutas-media',nome:'Tábua de frios média',descricao:'Composição intermediária com salame, queijo, azeitonas e petiscos. Valor estimado.',categoria:'tabua-frios-frutas',preco:15200,espaco:8,quantidadeMaxima:1,imagem:'assets/produtos/tabua-frios-media.webp',disponivel:true,destaque:true},
{id:'tabua-frios-premium',nome:'Tábua de frios premium',descricao:'Modelo maior com frios, queijos, ovos, chips, castanhas e molhos. Valor estimado.',categoria:'tabua-frios-frutas',preco:19700,espaco:10,quantidadeMaxima:1,imagem:'assets/produtos/tabua-frios-premium.webp',disponivel:true,destaque:true},
{id:'tabua-frutas',nome:'Seleção de frutas',descricao:'Frutas para deixar a cesta mais completa.',categoria:'tabua-frios-frutas',preco:6200,espaco:5,quantidadeMaxima:1,imagem:'assets/produtos/selecao-frutas-uvas-verdes.webp',disponivel:true,destaque:true},{id:'balao',nome:'Balão decorativo',descricao:'Acabamento visual para deixar a surpresa mais marcante.',categoria:'adicionais',preco:1600,espaco:2,quantidadeMaxima:3,imagem:'../assets/optimized/products/buque-te-amo-romantico.jpg',disponivel:true,destaque:false},
{id:'fotos-impressas',nome:'Fotografias',descricao:'Fotos impressas para personalizar a cesta.',categoria:'adicionais',preco:1800,espaco:1,quantidadeMaxima:6,imagem:'../assets/optimized/products/kit-vela-presente-especial.jpg',disponivel:true,destaque:true},
{id:'cartao-personalizado',nome:'Carta personalizada',descricao:'Mensagem impressa ou escrita à mão.',categoria:'adicionais',preco:1800,espaco:1,quantidadeMaxima:1,imagem:'assets/produtos/carta-personalizada.webp',disponivel:true,destaque:true}
,
{id:'kit-kat',nome:'Kit Kat',descricao:'Kit Kat para compor a cesta.',categoria:'chocolates',preco:700,espaco:1,quantidadeMaxima:10,imagem:'assets/produtos/kit-kat.webp',disponivel:true,destaque:false},
{id:'talento',nome:'Talento',descricao:'Chocolate Talento para a cesta.',categoria:'chocolates',preco:2600,espaco:1,quantidadeMaxima:6,imagem:'assets/produtos/talento-chocolate.webp',disponivel:true,destaque:false},
{id:'caixa-nestle',nome:'Caixa Nestlé',descricao:'Caixa de chocolates Nestlé.',categoria:'chocolates',preco:5800,espaco:3,quantidadeMaxima:4,imagem:'assets/produtos/caixa-nestle.webp',disponivel:true,destaque:false},
{id:'caixa-garoto',nome:'Caixa Garoto',descricao:'Caixa de chocolates Garoto.',categoria:'chocolates',preco:5800,espaco:3,quantidadeMaxima:4,imagem:'assets/produtos/caixa-garoto.webp',disponivel:true,destaque:false},
{id:'barra-nestle',nome:'Barra Nestlé',descricao:'Barra de chocolate Nestlé.',categoria:'chocolates',preco:2200,espaco:1,quantidadeMaxima:10,imagem:'assets/produtos/barra-nestle.webp',disponivel:true,destaque:false},
{id:'nutella',nome:'Nutella',descricao:'Creme de avelã Nutella para compor a cesta.',categoria:'chocolates',preco:4400,espaco:2,quantidadeMaxima:3,imagem:'assets/produtos/nutella.webp',disponivel:true,destaque:false},
{id:'hersheys',nome:"Hershey's",descricao:"Barra Hershey's para compor a cesta.",categoria:'chocolates',preco:2200,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'cookies',nome:'Cookies',descricao:'Cookies para a cesta.',categoria:'chocolates',preco:1400,espaco:1,quantidadeMaxima:8,imagem:'',disponivel:true,destaque:false},
{id:'wafer',nome:'Wafer',descricao:'Wafer para compor a cesta.',categoria:'chocolates',preco:1200,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'marshmallow',nome:'Marshmallow',descricao:'Marshmallow para compor a cesta.',categoria:'chocolates',preco:1300,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},

{id:'cafe-tradicional',nome:'Café tradicional',descricao:'Café em pó para cesta de café da manhã.',categoria:'bebidas',preco:2200,espaco:2,quantidadeMaxima:3,imagem:'',disponivel:true,destaque:false},
{id:'cappuccino',nome:'Cappuccino',descricao:'Cappuccino pronto para a cesta.',categoria:'bebidas',preco:2200,espaco:1,quantidadeMaxima:6,imagem:'assets/produtos/cappuccino-sache.webp',disponivel:true,destaque:false},
{id:'achocolatado',nome:'Achocolatado Nescau',descricao:'Achocolatado para compor cesta.',categoria:'bebidas',preco:1900,espaco:1,quantidadeMaxima:6,imagem:'assets/produtos/achocolatado-nescau.webp',disponivel:true,destaque:false},
{id:'chocolate-quente',nome:'Chocolate quente',descricao:'Mix para chocolate quente.',categoria:'bebidas',preco:2100,espaco:1,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'cha',nome:'Chá',descricao:'Sache ou caixa de chá para cesta.',categoria:'bebidas',preco:1600,espaco:1,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'achocolatado-toddy',nome:'Achocolatado Toddy',descricao:'Achocolatado para cesta infantil ou café da manhã.',categoria:'bebidas',preco:1900,espaco:1,quantidadeMaxima:6,imagem:'assets/produtos/achocolatado-todinho.webp',disponivel:true,destaque:false},
{id:'leite-piracanjuba',nome:'Leite Piracanjuba',descricao:'Leite para compor cesta de café da manhã.',categoria:'bebidas',preco:2200,espaco:2,quantidadeMaxima:4,imagem:'assets/produtos/leite-piracanjuba.webp',disponivel:true,destaque:false},
{id:'suco-uva-kapo',nome:'Suco de uva Kapo',descricao:'Suco individual para cesta infantil ou café da manhã.',categoria:'bebidas',preco:1000,espaco:1,quantidadeMaxima:6,imagem:'assets/produtos/suco-uva-kapo.webp',disponivel:true,destaque:false},
{id:'suco-uva-aurora',nome:'Suco de uva Aurora',descricao:'Suco de uva para composição especial.',categoria:'bebidas',preco:3500,espaco:3,quantidadeMaxima:2,imagem:'assets/produtos/suco-uva-aurora.webp',disponivel:true,destaque:false},
{id:'iogurte-morango',nome:'Iogurte de morango',descricao:'Iogurte sabor morango para cesta de café da manhã.',categoria:'bebidas',preco:1600,espaco:1,quantidadeMaxima:6,imagem:'assets/produtos/iogurte-morango.webp',disponivel:true,destaque:false},
{id:'iogurte-frutas-vermelhas',nome:'Iogurte frutas vermelhas',descricao:'Iogurte sabor frutas vermelhas para cesta.',categoria:'bebidas',preco:1900,espaco:1,quantidadeMaxima:6,imagem:'assets/produtos/iogurte-aurora-frutas-vermelhas.webp',disponivel:true,destaque:false},
{id:'danone',nome:'Danone',descricao:'Danone para compor cesta de café da manhã.',categoria:'bebidas',preco:1600,espaco:1,quantidadeMaxima:6,imagem:'assets/produtos/danone.webp',disponivel:true,destaque:false},
{id:'pao-frances',nome:'Pão francês (fresco)',descricao:'Pão francês para cesta de café da manhã.',categoria:'tabua-frios-frutas',preco:1300,espaco:2,quantidadeMaxima:6,imagem:'assets/produtos/pao-frances.webp',disponivel:true,destaque:false},
{id:'croissant',nome:'Mini croissant',descricao:'Mini croissant fresco para cesta.',categoria:'tabua-frios-frutas',preco:1600,espaco:2,quantidadeMaxima:6,imagem:'assets/produtos/mini-croissant.webp',disponivel:true,destaque:false},
{id:'torradas',nome:'Torradas',descricao:'Torradas para café da manhã.',categoria:'tabua-frios-frutas',preco:1400,espaco:1,quantidadeMaxima:6,imagem:'assets/produtos/biscoitos-bauducco.webp',disponivel:true,destaque:false},
{id:'biscoitos-cafe',nome:'Biscoitos Bauducco',descricao:'Biscoitos para cesta de café.',categoria:'tabua-frios-frutas',preco:1400,espaco:1,quantidadeMaxima:8,imagem:'assets/produtos/biscoito-bauducco.webp',disponivel:true,destaque:false},
{id:'biscoito-passatempo',nome:'Biscoito Passatempo',descricao:'Biscoito Passatempo para compor a cesta.',categoria:'tabua-frios-frutas',preco:900,espaco:1,quantidadeMaxima:8,imagem:'assets/produtos/biscoito-passatempo.webp',disponivel:true,destaque:false},
{id:'club-social',nome:'Club Social',descricao:'Salgadinho Club Social para cesta de lanche.',categoria:'tabua-frios-frutas',preco:1000,espaco:1,quantidadeMaxima:8,imagem:'assets/produtos/club-social.webp',disponivel:true,destaque:false},
{id:'geleia',nome:'Geleia de frutas vermelhas',descricao:'Geleia para compor cesta de café.',categoria:'tabua-frios-frutas',preco:2400,espaco:1,quantidadeMaxima:4,imagem:'assets/produtos/geleia-frutas-vermelhas.webp',disponivel:true,destaque:false},
{id:'mel',nome:'Mel',descricao:'Mel para compor cesta de café.',categoria:'tabua-frios-frutas',preco:2600,espaco:1,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'requeijao',nome:'Requeijão',descricao:'Requeijão para cesta de café.',categoria:'tabua-frios-frutas',preco:2200,espaco:2,quantidadeMaxima:4,imagem:'assets/produtos/requeijao-vigor.webp',disponivel:true,destaque:false},
{id:'pao-massa-fina',nome:'Pão massa fina',descricao:'Pão massa fina para cesta de café da manhã.',categoria:'tabua-frios-frutas',preco:1300,espaco:2,quantidadeMaxima:6,imagem:'assets/produtos/pao-massa-fina.webp',disponivel:true,destaque:false},
{id:'pao-massa-grossa',nome:'Pão massa grossa',descricao:'Pão massa grossa para cesta de café da manhã.',categoria:'tabua-frios-frutas',preco:1200,espaco:2,quantidadeMaxima:6,imagem:'assets/produtos/pao-massa-grossa.webp',disponivel:true,destaque:false},
{id:'bolo-simples-cafe',nome:'Bolo simples para cesta',descricao:'Bolo simples para cesta de café da manhã.',categoria:'tabua-frios-frutas',preco:4400,espaco:5,quantidadeMaxima:2,imagem:'assets/produtos/bolo-simples-cafe.webp',disponivel:true,destaque:false},
{id:'fatia-bolo-chocolate',nome:'Fatia de bolo de chocolate',descricao:'Fatia de bolo de chocolate para complementar a cesta.',categoria:'tabua-frios-frutas',preco:2100,espaco:2,quantidadeMaxima:4,imagem:'assets/produtos/fatia-bolo-chocolate.webp',disponivel:true,destaque:false},
{id:'mini-bolo-aniversario',nome:'Mini bolo de aniversário',descricao:'Mini bolo decorado para cesta especial.',categoria:'tabua-frios-frutas',preco:7200,espaco:6,quantidadeMaxima:1,imagem:'assets/produtos/mini-bolo-aniversario.webp',disponivel:true,destaque:false},
{id:'bolo-chocolate-morango',nome:'Mini bolo chocolate com morango',descricao:'Mini bolo de chocolate com morangos para surpresa especial.',categoria:'tabua-frios-frutas',preco:8000,espaco:6,quantidadeMaxima:1,imagem:'assets/produtos/bolo-chocolate-morango-aniversario.webp',disponivel:true,destaque:false},
{id:'bolo-confeitado-feminino',nome:'Bolo confeitado feminino',descricao:'Bolo confeitado para composição premium.',categoria:'tabua-frios-frutas',preco:17900,espaco:8,quantidadeMaxima:1,imagem:'assets/produtos/bolo-confeitado-feminino.webp',disponivel:true,destaque:false},
{id:'bolo-bailarina-chocolate',nome:'Bolo bailarina chocolate 2 kg',descricao:'Bolo temático de chocolate 2 kg para composição especial.',categoria:'tabua-frios-frutas',preco:20400,espaco:8,quantidadeMaxima:1,imagem:'assets/produtos/bolo-bailarina-chocolate.webp',disponivel:true,destaque:false},
{id:'salgados-variados',nome:'Salgados variados',descricao:'Porção de salgados variados para cesta de lanche.',categoria:'tabua-frios-frutas',preco:6200,espaco:5,quantidadeMaxima:2,imagem:'assets/produtos/salgados-variados.webp',disponivel:true,destaque:false},

{id:'queijo',nome:'Queijo fatiado',descricao:'Queijo para compor tábua de frios.',categoria:'tabua-frios-frutas',preco:3100,espaco:3,quantidadeMaxima:2,imagem:'assets/produtos/queijo-fatiado.webp',disponivel:true,destaque:false},
{id:'presunto',nome:'Presunto fatiado',descricao:'Presunto para tábua de frios.',categoria:'tabua-frios-frutas',preco:2700,espaco:3,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},
{id:'salame',nome:'Salame fatiado',descricao:'Salame para tábua de frios.',categoria:'tabua-frios-frutas',preco:2400,espaco:3,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},

{id:'uva',nome:'Uva',descricao:'Uvas frescas para compor a cesta.',categoria:'tabua-frios-frutas',preco:2400,espaco:2,quantidadeMaxima:2,imagem:'assets/produtos/uva.webp',disponivel:true,destaque:false},
{id:'maca',nome:'Maçã',descricao:'Maçã para compor a cesta.',categoria:'tabua-frios-frutas',preco:1800,espaco:2,quantidadeMaxima:4,imagem:'assets/produtos/maca.webp',disponivel:true,destaque:false},
{id:'pera',nome:'Pera',descricao:'Pera para compor a cesta.',categoria:'tabua-frios-frutas',preco:1800,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'kiwi',nome:'Kiwi',descricao:'Kiwi para compor a cesta.',categoria:'tabua-frios-frutas',preco:1600,espaco:2,quantidadeMaxima:4,imagem:'assets/produtos/kiwi.webp',disponivel:true,destaque:false},
{id:'morango',nome:'Morango',descricao:'Morango para compor a cesta.',categoria:'tabua-frios-frutas',preco:2100,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'banana',nome:'Banana',descricao:'Banana para compor a cesta.',categoria:'tabua-frios-frutas',preco:1300,espaco:2,quantidadeMaxima:6,imagem:'assets/produtos/banana.webp',disponivel:true,destaque:false},

{id:'rosa-branca',nome:'Rosa branca',descricao:'Rosa branca para decoração.',categoria:'flores-decoracao',preco:3100,espaco:2,quantidadeMaxima:6,imagem:'assets/produtos/rosa-branca.webp',disponivel:true,destaque:false},
{id:'rosa-rosa',nome:'Rosa rosa',descricao:'Rosa rosa para decoração.',categoria:'flores-decoracao',preco:3100,espaco:2,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'rosa-perfumada',nome:'Rosa perfumada',descricao:'Rosa perfumada para presente.',categoria:'flores-decoracao',preco:3500,espaco:3,quantidadeMaxima:4,imagem:'assets/produtos/rosa-vermelha-natural.webp',disponivel:true,destaque:false},
{id:'mini-arranjo',nome:'Mini arranjo',descricao:'Mini arranjo para compor a cesta.',categoria:'flores-decoracao',preco:3500,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'buque-compacto',nome:'Buquê compacto',descricao:'Buquê compacto para presente.',categoria:'flores-decoracao',preco:8500,espaco:4,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},

{id:'porta-retrato',nome:'Porta-retrato',descricao:'Porta-retrato para presente.',categoria:'presentes',preco:3500,espaco:3,quantidadeMaxima:2,imagem:'assets/produtos/porta-retrato.webp',disponivel:true,destaque:false},
{id:'quadro',nome:'Quadro decorativo',descricao:'Quadro para decorar o presente.',categoria:'presentes',preco:6200,espaco:6,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'agenda',nome:'Agenda',descricao:'Agenda para presente.',categoria:'presentes',preco:3500,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'caderno',nome:'Caderno',descricao:'Caderno para presente.',categoria:'presentes',preco:2600,espaco:2,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},

{id:'campari',nome:'Campari',descricao:'Campari para compor a cesta (álcool).',categoria:'bebidas',preco:26000,espaco:8,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'espumante',nome:'Espumante',descricao:'Espumante para celebrar.',categoria:'bebidas',preco:11600,espaco:8,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},

{id:'copo-whisky',nome:'Copo de Whisky',descricao:'Copo de whisky como mimo.',categoria:'presentes',preco:4400,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'taca-vinho',nome:'Taça de vinho',descricao:'Taça de vinho para a cesta.',categoria:'presentes',preco:3100,espaco:2,quantidadeMaxima:4,imagem:'assets/produtos/taca-vinho.webp',disponivel:true,destaque:false},


{id:'laco',nome:'Laço decorativo',descricao:'Laço para acabamento da cesta.',categoria:'adicionais',preco:700,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'papel-seda',nome:'Papel seda',descricao:'Papel seda para embrulho.',categoria:'adicionais',preco:400,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'celofane',nome:'Celofane',descricao:'Celofane para embrulho.',categoria:'adicionais',preco:700,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'fita-decorativa',nome:'Fita decorativa',descricao:'Fita decorativa para acabamento.',categoria:'adicionais',preco:700,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'palha-decorativa',nome:'Palha decorativa',descricao:'Palha decorativa para acabamento.',categoria:'adicionais',preco:600,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'caixa-decorativa',nome:'Caixa decorativa',descricao:'Caixa decorativa para apresentação.',categoria:'adicionais',preco:2600,espaco:4,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'cesta-vime',nome:'Cesta de vime',descricao:'Cesta de vime para montagem.',categoria:'adicionais',preco:5300,espaco:8,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},
{id:'box-decorativo',nome:'Box decorativo',descricao:'Box decorativo para presentes.',categoria:'adicionais',preco:3500,espaco:6,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},
{id:'bandeja',nome:'Bandeja',descricao:'Bandeja para apresentação.',categoria:'adicionais',preco:4300,espaco:6,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},

{id:'cartao',nome:'Cartão',descricao:'Cartão simples para mensagem.',categoria:'adicionais',preco:900,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'nome-personalizado',nome:'Nome personalizado',descricao:'Nome personalizado para a decoração.',categoria:'adicionais',preco:1300,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'mensagem-personalizada',nome:'Mensagem personalizada',descricao:'Mensagem personalizada para cartão.',categoria:'adicionais',preco:1300,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'tema-personalizado',nome:'Tema personalizado',descricao:'Tema de decoração personalizado.',categoria:'adicionais',preco:1800,espaco:2,quantidadeMaxima:5,imagem:'',disponivel:true,destaque:false},
{id:'cor-decoracao',nome:'Cor da decoração',descricao:'Escolha de cor para a decoração.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},

{id:'ocasiacao-aniversario',nome:'Ocasião: Aniversário',descricao:'Marca a cesta para aniversário.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-romantico',nome:'Ocasião: Romântico',descricao:'Marca a cesta como romântica.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-dia-dos-pais',nome:'Ocasião: Dia dos Pais',descricao:'Marca a cesta para Dia dos Pais.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-dia-das-maes',nome:'Ocasião: Dia das Mães',descricao:'Marca a cesta para Dia das Mães.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-cafe-da-manha',nome:'Ocasião: Café da manhã',descricao:'Marca a cesta como café da manhã.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-agradecimento',nome:'Ocasião: Agradecimento',descricao:'Marca a cesta como agradecimento.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-pedido-desculpas',nome:'Ocasião: Pedido de desculpas',descricao:'Marca a cesta para pedido de desculpas.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-conquista',nome:'Ocasião: Conquista',descricao:'Marca a cesta para comemorar conquista.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-formatura',nome:'Ocasião: Formatura',descricao:'Marca a cesta para formatura.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-casamento',nome:'Ocasião: Casamento',descricao:'Marca a cesta para casamento.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-noivado',nome:'Ocasião: Noivado',descricao:'Marca a cesta para noivado.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-surpresa',nome:'Ocasião: Surpresa',descricao:'Marca a cesta para surpresa.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false}
];})(window);
