(function(w){const N=w.ZadoniCesta;N.categorias=[{id:'chocolates',nome:'Chocolates'},{id:'bebidas',nome:'Bebidas'},{id:'flores-decoracao',nome:'Flores e decoração'},{id:'presentes',nome:'Presentes'},{id:'tabua-frios-frutas',nome:'Tábua de frios e frutas'},{id:'adicionais',nome:'Adicionais'}];
// ATENÇÃO: substituir pelos preços, produtos e disponibilidade reais da Zadoni.
N.produtos=[
{id:'ferrero-rocher-12',nome:'Ferrero Rocher caixa 12 unidades',descricao:'Caixa com 12 unidades de Ferrero Rocher.',categoria:'chocolates',preco:6200,espaco:4,quantidadeMaxima:2,imagem:'assets/produtos/ferrero-rocher-caixa-12.webp',disponivel:true,destaque:true},
{id:'ferrero-rocher-8',nome:'Ferrero Rocher caixa 8 unidades',descricao:'Caixa com 8 unidades de Ferrero Rocher.',categoria:'chocolates',preco:5500,espaco:4,quantidadeMaxima:2,imagem:'assets/produtos/ferrero-rocher-caixa-8.webp',disponivel:true,destaque:true},
{id:'ferrero-rocher-4',nome:'Ferrero Rocher caixa 4 unidades',descricao:'Caixa com 4 unidades de Ferrero Rocher.',categoria:'chocolates',preco:3800,espaco:2,quantidadeMaxima:3,imagem:'assets/produtos/ferrero-rocher-caixa-4.webp',disponivel:true,destaque:true},
{id:'barrinha-cacau-show',nome:'Barrinha Cacau Show',descricao:'Barrinha Cacau Show para compor a cesta.',categoria:'chocolates',preco:1000,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:true},
{id:'bebida-especial',nome:'Bebida especial',descricao:'Suco, refrigerante ou similar a confirmar.',categoria:'bebidas',preco:3200,espaco:3,quantidadeMaxima:3,imagem:'../assets/optimized/products/mimo-coca-cola-criativo.jpg',disponivel:true,destaque:true},
{id:'vinho-pergola',nome:'Vinho Pérgola',descricao:'Vinho Pérgola para composição especial.',categoria:'bebidas',preco:6500,espaco:6,quantidadeMaxima:1,imagem:'../assets/optimized/products/cesta-romantica-vinho-san-martin.jpg',disponivel:true,destaque:true},
{id:'bebida-cafe',nome:'Bebida para café',descricao:'Item para cesta de café da manhã.',categoria:'bebidas',preco:1800,espaco:2,quantidadeMaxima:3,imagem:'../assets/optimized/products/cesta-cafe-da-manha-especial.webp',disponivel:true,destaque:false},
{id:'arranjo-rosas-naturais',nome:'Arranjo de rosas naturais',descricao:'Arranjo de rosas naturais para colocar na cesta.',categoria:'flores-decoracao',preco:8900,espaco:5,quantidadeMaxima:1,imagem:'../assets/optimized/products/jarro-flor-natural-laco-rosa.jpg',disponivel:true,destaque:true},
{id:'arranjo-rosas-artificiais',nome:'Arranjo de rosas artificiais',descricao:'Arranjo de rosas artificiais para compor a cesta.',categoria:'flores-decoracao',preco:3900,espaco:3,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:true},
{id:'arranjo-vermelho',nome:'Arranjo vermelho',descricao:'Arranjo com presença para ocasiões especiais.',categoria:'flores-decoracao',preco:7500,espaco:5,quantidadeMaxima:1,imagem:'../assets/optimized/products/jarro-flores-naturais-vermelho.jpg',disponivel:true,destaque:true},
{id:'detalhe-girassol',nome:'Detalhe girassol',descricao:'Elemento alegre para decoração da cesta.',categoria:'flores-decoracao',preco:3900,espaco:3,quantidadeMaxima:2,imagem:'../assets/optimized/products/box-girassol-com-caixa.jpg',disponivel:true,destaque:false},
{id:'caneca-presente',nome:'Caneca para presente',descricao:'Caneca para deixar a cesta mais útil e afetiva.',categoria:'presentes',preco:3900,espaco:4,quantidadeMaxima:2,imagem:'../assets/optimized/products/cesta-masculina-azul-classica.jpg',disponivel:true,destaque:true},
{id:'pelucia',nome:'Pelúcia',descricao:'Pelúcia decorativa para complementar o presente.',categoria:'presentes',preco:5500,espaco:8,quantidadeMaxima:1,imagem:'../assets/optimized/products/mimo-amor-perfeito-trufas-pelucia.jpg',disponivel:true,destaque:true},
{id:'perfume-bolso',nome:'Perfume de bolso',descricao:'Fragrância 15 ml conforme disponibilidade.',categoria:'presentes',preco:4700,espaco:2,quantidadeMaxima:3,imagem:'../assets/optimized/products/perfume-521-vip-rose-amakha-15ml.jpg',disponivel:true,destaque:true},
{id:'tabua-frios-pequena',nome:'Tábua de frios pequena',descricao:'Opção menor de frios para complementar a cesta.',categoria:'tabua-frios-frutas',preco:6900,espaco:6,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:true},
{id:'tabua-frios-frutas-media',nome:'Tábua de frios e frutas média',descricao:'Composição intermediária com frios e frutas.',categoria:'tabua-frios-frutas',preco:9900,espaco:8,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:true},
{id:'tabua-frutas',nome:'Seleção de frutas',descricao:'Frutas para deixar a cesta mais completa.',categoria:'tabua-frios-frutas',preco:4500,espaco:5,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:true},{id:'balao',nome:'Balão decorativo',descricao:'Acabamento visual para deixar a surpresa mais marcante.',categoria:'adicionais',preco:1000,espaco:2,quantidadeMaxima:3,imagem:'../assets/optimized/products/buque-te-amo-romantico.jpg',disponivel:true,destaque:false},
{id:'fotos-impressas',nome:'Fotografias',descricao:'Fotos impressas para personalizar a cesta.',categoria:'adicionais',preco:1500,espaco:1,quantidadeMaxima:6,imagem:'../assets/optimized/products/kit-vela-presente-especial.jpg',disponivel:true,destaque:true},
{id:'cartao-personalizado',nome:'Carta personalizada',descricao:'Mensagem impressa ou escrita à mão.',categoria:'adicionais',preco:1500,espaco:1,quantidadeMaxima:1,imagem:'../assets/optimized/products/mimo-carinho-especial.jpg',disponivel:true,destaque:true}
,
{id:'rafaello',nome:'Rafaello',descricao:'Rafaello para compor a cesta.',categoria:'chocolates',preco:4200,espaco:2,quantidadeMaxima:3,imagem:'',disponivel:true,destaque:false},
{id:'lindt',nome:'Lindt',descricao:'Lindt para compor a cesta.',categoria:'chocolates',preco:4500,espaco:2,quantidadeMaxima:5,imagem:'',disponivel:true,destaque:false},
{id:'kinder-bueno',nome:'Kinder Bueno',descricao:'Kinder Bueno para compor a cesta.',categoria:'chocolates',preco:1800,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'kit-kat',nome:'Kit Kat',descricao:'Kit Kat para compor a cesta.',categoria:'chocolates',preco:1200,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'talento',nome:'Talento',descricao:'Chocolate Talento para a cesta.',categoria:'chocolates',preco:2200,espaco:1,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'lacta-favoritos',nome:'Lacta Favoritos',descricao:'Seleção Lacta Favoritos.',categoria:'chocolates',preco:2600,espaco:2,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'caixa-nestle',nome:'Caixa Nestlé',descricao:'Caixa de chocolates Nestlé.',categoria:'chocolates',preco:2800,espaco:3,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'caixa-garoto',nome:'Caixa Garoto',descricao:'Caixa de chocolates Garoto.',categoria:'chocolates',preco:2400,espaco:3,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'barra-lacta',nome:'Barra Lacta',descricao:'Barra de chocolate Lacta.',categoria:'chocolates',preco:900,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'barra-nestle',nome:'Barra Nestlé',descricao:'Barra de chocolate Nestlé.',categoria:'chocolates',preco:900,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'hersheys',nome:"Hershey's",descricao:"Barra Hershey's para compor a cesta.",categoria:'chocolates',preco:950,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'milka',nome:'Milka',descricao:'Chocolate Milka para compor a cesta.',categoria:'chocolates',preco:1200,espaco:1,quantidadeMaxima:8,imagem:'',disponivel:true,destaque:false},
{id:'oreo',nome:'Oreo',descricao:'Oreo para complementar a cesta.',categoria:'chocolates',preco:1100,espaco:1,quantidadeMaxima:8,imagem:'',disponivel:true,destaque:false},
{id:'cookies',nome:'Cookies',descricao:'Cookies para a cesta.',categoria:'chocolates',preco:1000,espaco:1,quantidadeMaxima:8,imagem:'',disponivel:true,destaque:false},
{id:'wafer',nome:'Wafer',descricao:'Wafer para compor a cesta.',categoria:'chocolates',preco:900,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'amendoim-confeitado',nome:'Amendoim confeitado',descricao:'Amendoim confeitado para compor a cesta.',categoria:'tabua-frios-frutas',preco:1200,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'marshmallow',nome:'Marshmallow',descricao:'Marshmallow para compor a cesta.',categoria:'chocolates',preco:800,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},

{id:'cafe-tradicional',nome:'Café tradicional',descricao:'Café em pó para cesta de café da manhã.',categoria:'bebidas',preco:1800,espaco:2,quantidadeMaxima:3,imagem:'',disponivel:true,destaque:false},
{id:'cappuccino',nome:'Cappuccino',descricao:'Cappuccino pronto para a cesta.',categoria:'bebidas',preco:1400,espaco:1,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'achocolatado',nome:'Achocolatado',descricao:'Achocolatado para compor cesta.',categoria:'bebidas',preco:1200,espaco:1,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'chocolate-quente',nome:'Chocolate quente',descricao:'Mix para chocolate quente.',categoria:'bebidas',preco:1200,espaco:1,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'cha',nome:'Chá',descricao:'Sache ou caixa de chá para cesta.',categoria:'bebidas',preco:900,espaco:1,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'pao-frances',nome:'Pão francês (fresco)',descricao:'Pão francês para cesta de café da manhã.',categoria:'tabua-frios-frutas',preco:800,espaco:2,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'croissant',nome:'Croissant',descricao:'Croissant fresco para cesta.',categoria:'tabua-frios-frutas',preco:1200,espaco:2,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'torradas',nome:'Torradas',descricao:'Torradas para café da manhã.',categoria:'tabua-frios-frutas',preco:800,espaco:1,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'biscoitos-cafe',nome:'Biscoitos',descricao:'Biscoitos para cesta de café.',categoria:'tabua-frios-frutas',preco:900,espaco:1,quantidadeMaxima:8,imagem:'',disponivel:true,destaque:false},
{id:'geleia',nome:'Geleia',descricao:'Geleia artesanal para compor cesta.',categoria:'tabua-frios-frutas',preco:1100,espaco:1,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'mel',nome:'Mel',descricao:'Mel para compor cesta de café.',categoria:'tabua-frios-frutas',preco:1300,espaco:1,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'requeijao',nome:'Requeijão',descricao:'Requeijão para cesta de café.',categoria:'tabua-frios-frutas',preco:1500,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'manteiga',nome:'Manteiga',descricao:'Manteiga para cesta de café da manhã.',categoria:'tabua-frios-frutas',preco:900,espaco:1,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},

{id:'queijo',nome:'Queijo fatiado',descricao:'Queijo para compor tábua de frios.',categoria:'tabua-frios-frutas',preco:3900,espaco:3,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},
{id:'presunto',nome:'Presunto fatiado',descricao:'Presunto para tábua de frios.',categoria:'tabua-frios-frutas',preco:2900,espaco:3,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},
{id:'salame',nome:'Salame fatiado',descricao:'Salame para tábua de frios.',categoria:'tabua-frios-frutas',preco:3200,espaco:3,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},
{id:'peito-peru',nome:'Peito de peru fatiado',descricao:'Peito de peru para tábua de frios.',categoria:'tabua-frios-frutas',preco:3500,espaco:3,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},

{id:'uva',nome:'Uva',descricao:'Uvas frescas para compor a cesta.',categoria:'tabua-frios-frutas',preco:1200,espaco:2,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},
{id:'maca',nome:'Maçã',descricao:'Maçã para compor a cesta.',categoria:'tabua-frios-frutas',preco:1000,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'pera',nome:'Pera',descricao:'Pera para compor a cesta.',categoria:'tabua-frios-frutas',preco:1100,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'kiwi',nome:'Kiwi',descricao:'Kiwi para compor a cesta.',categoria:'tabua-frios-frutas',preco:1500,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'morango',nome:'Morango',descricao:'Morango para compor a cesta.',categoria:'tabua-frios-frutas',preco:1400,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'banana',nome:'Banana',descricao:'Banana para compor a cesta.',categoria:'tabua-frios-frutas',preco:900,espaco:2,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'laranja',nome:'Laranja',descricao:'Laranja para compor a cesta.',categoria:'tabua-frios-frutas',preco:900,espaco:2,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},

{id:'rosa-branca',nome:'Rosa branca',descricao:'Rosa branca para decoração.',categoria:'flores-decoracao',preco:2200,espaco:2,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'rosa-rosa',nome:'Rosa rosa',descricao:'Rosa rosa para decoração.',categoria:'flores-decoracao',preco:2200,espaco:2,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'rosa-perfumada',nome:'Rosa perfumada',descricao:'Rosa perfumada para presente.',categoria:'flores-decoracao',preco:3200,espaco:3,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'mini-arranjo',nome:'Mini arranjo',descricao:'Mini arranjo para compor a cesta.',categoria:'flores-decoracao',preco:1900,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'buque-compacto',nome:'Buquê compacto',descricao:'Buquê compacto para presente.',categoria:'flores-decoracao',preco:4500,espaco:4,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},

{id:'porta-retrato',nome:'Porta-retrato',descricao:'Porta-retrato para presente.',categoria:'presentes',preco:2200,espaco:3,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},
{id:'quadro',nome:'Quadro decorativo',descricao:'Quadro para decorar o presente.',categoria:'presentes',preco:4500,espaco:6,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'chaveiro',nome:'Chaveiro',descricao:'Chaveiro personalizado.',categoria:'presentes',preco:800,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'almofada',nome:'Almofada',descricao:'Almofada decorativa.',categoria:'presentes',preco:3900,espaco:6,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},
{id:'agenda',nome:'Agenda',descricao:'Agenda para presente.',categoria:'presentes',preco:2500,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'caderno',nome:'Caderno',descricao:'Caderno para presente.',categoria:'presentes',preco:1800,espaco:2,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},

{id:'campari',nome:'Campari',descricao:'Campari para compor a cesta (álcool).',categoria:'bebidas',preco:22000,espaco:8,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'espumante',nome:'Espumante',descricao:'Espumante para celebrar.',categoria:'bebidas',preco:42000,espaco:8,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'whisky',nome:'Whisky',descricao:'Whisky para compor a cesta.',categoria:'bebidas',preco:85000,espaco:10,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},

{id:'copo-whisky',nome:'Copo de Whisky',descricao:'Copo de whisky como mimo.',categoria:'presentes',preco:1500,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'taca-vinho',nome:'Taça de vinho',descricao:'Taça de vinho para a cesta.',categoria:'presentes',preco:1500,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'taca-espumante',nome:'Taça de espumante',descricao:'Taça de espumante para a cesta.',categoria:'presentes',preco:1500,espaco:2,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},

{id:'amendoim',nome:'Amendoim',descricao:'Amendoim (simples) para tábua.',categoria:'tabua-frios-frutas',preco:900,espaco:1,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},
{id:'castanhas',nome:'Castanhas',descricao:'Castanhas para tábua de frios.',categoria:'tabua-frios-frutas',preco:1800,espaco:1,quantidadeMaxima:6,imagem:'',disponivel:true,destaque:false},

{id:'laco',nome:'Laço decorativo',descricao:'Laço para acabamento da cesta.',categoria:'adicionais',preco:300,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'papel-seda',nome:'Papel seda',descricao:'Papel seda para embrulho.',categoria:'adicionais',preco:200,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'celofane',nome:'Celofane',descricao:'Celofane para embrulho.',categoria:'adicionais',preco:300,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'fita-decorativa',nome:'Fita decorativa',descricao:'Fita decorativa para acabamento.',categoria:'adicionais',preco:300,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'palha-decorativa',nome:'Palha decorativa',descricao:'Palha decorativa para acabamento.',categoria:'adicionais',preco:300,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'caixa-decorativa',nome:'Caixa decorativa',descricao:'Caixa decorativa para apresentação.',categoria:'adicionais',preco:1200,espaco:4,quantidadeMaxima:4,imagem:'',disponivel:true,destaque:false},
{id:'cesta-vime',nome:'Cesta de vime',descricao:'Cesta de vime para montagem.',categoria:'adicionais',preco:3500,espaco:8,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},
{id:'box-decorativo',nome:'Box decorativo',descricao:'Box decorativo para presentes.',categoria:'adicionais',preco:2200,espaco:6,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},
{id:'bandeja',nome:'Bandeja',descricao:'Bandeja para apresentação.',categoria:'adicionais',preco:2200,espaco:6,quantidadeMaxima:2,imagem:'',disponivel:true,destaque:false},

{id:'cartao',nome:'Cartão',descricao:'Cartão simples para mensagem.',categoria:'adicionais',preco:500,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'nome-personalizado',nome:'Nome personalizado',descricao:'Nome personalizado para a decoração.',categoria:'adicionais',preco:800,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'mensagem-personalizada',nome:'Mensagem personalizada',descricao:'Mensagem personalizada para cartão.',categoria:'adicionais',preco:800,espaco:1,quantidadeMaxima:10,imagem:'',disponivel:true,destaque:false},
{id:'tema-personalizado',nome:'Tema personalizado',descricao:'Tema de decoração personalizado.',categoria:'adicionais',preco:1200,espaco:2,quantidadeMaxima:5,imagem:'',disponivel:true,destaque:false},
{id:'cor-decoracao',nome:'Cor da decoração',descricao:'Escolha de cor para a decoração.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},

{id:'ocasiacao-aniversario',nome:'Ocasião: Aniversário',descricao:'Marca a cesta para aniversário.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-romantico',nome:'Ocasião: Romântico',descricao:'Marca a cesta como romântica.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-dia-dos-pais',nome:'Ocasião: Dia dos Pais',descricao:'Marca a cesta para Dia dos Pais.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-dia-das-maes',nome:'Ocasião: Dia das Mães',descricao:'Marca a cesta para Dia das Mães.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-cafe-da-manha',nome:'Ocasião: Café da manhã',descricao:'Marca a cesta como café da manhã.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-agradecimento',nome:'Ocasião: Agradecimento',descricao:'Marca a cesta como agradecimento.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-pedido-desculpas',nome:'Ocasião: Pedido de desculpas',descricao:'Marca a cesta para pedido de desculpas.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-conquista',nome:'Ocasião: Conquista',descricao:'Marca a cesta para comemorar conquista.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-formatura',nome:'Ocasião: Formatura',descricao:'Marca a cesta para formatura.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-casamento',nome:'Ocasião: Casamento',descricao:'Marca a cesta para casamento.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-noivado',nome:'Ocasião: Noivado',descricao:'Marca a cesta para noivado.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false},
{id:'ocasiacao-surpresa',nome:'Ocasião: Surpresa',descricao:'Marca a cesta para surpresa.',categoria:'adicionais',preco:0,espaco:0,quantidadeMaxima:1,imagem:'',disponivel:true,destaque:false}
];})(window);
